import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Caudex } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

const getCaudex = Caudex({
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
})

const getCormorant = Cormorant_Garamond({
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getCormorant.className} ${getCaudex.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
